#!/bin/bash
set -xe
REMOTE_FQDN=google.com
REMOTE_HOST="$(dig -4 $REMOTE_FQDN +short|head -n1)"
REMOTE_PORT=443
LOCAL_HOST=127.0.0.150
LOCAL_PORT=15000
PROTO=https

echo REMOTE DOMAIN
curl -4k $PROTO://$REMOTE_FQDN:$REMOTE_PORT

sleep 1
echo REMOTE HOST
curl -4k $PROTO://$REMOTE_HOST:$REMOTE_PORT

sleep 1
echo LOCAL
curl -v4k $PROTO://$LOCAL_HOST:$LOCAL_PORT
