- name: test pb
  hosts: all
  gather_facts: no
  vars:
        ansible_ssh_port: 5986
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
  tasks:
        - name: Running test cmd.exe command on windows server
          register: cContents
          win_shell: dir c:\ chdir=c:\
        - name: Printing cContents data
          debug: var=cContents
